---
title: Destinesia
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
permalink: pretty
exclude:
- README.*
- LICENSE.txt
sass:
  style: compressed
name: Where the road ends and the fun begins.
subtitle: New Products Launching This Summer.
robots:
  description: my development serverless hosted site
  keywords: foo, bar, baz
  crawl: index,follow
url: https://glennrowe.github.io/destinesia.cloud.fuse-core.dev/
baseurl: ''
ga:
  account: 
  cookieconsent: true
  anonymizeip: true
avatar: https://avatars1.githubusercontent.com/u/2098980
links:
- linkedin:
    name: LinkedIn
    show: false
    href: https://linkedin.com/in/gwrowe/
    icon: fab fa-linkedin
- twitter:
    name: Twitter
    show: true
    href: https://twitter.com/countylinesc
    icon: fab fa-twitter
- facebook:
    name: Facebook
    show: false
    href: https://facebook.com/countylineoutfitters
    icon: fab fa-facebook
- instagram:
    name: Instagram
    show: false
    href: https://instagram.com/countylinesc
    icon: fab fa-instagram
- email:
    name: Email
    show: true
    href: mailto:glennrowe@countylineoutfitters.co
    icon: fas fa-envelope
extra_html: https://countylineoutfitters.co
